
import Head from 'next/head'
import SocailHeader from "../components/SocialHeader"
import Footer from '../components/Footer'
import CopyRight from '../components/CopyRight'
import Choose from '../components/Choose'
import Newsletter from '../components/Newsletter'
import Header from '../components/Header'
import FeaturedCategories from '../components/FeaturedCategories'
import PhoneBar from '../components/PhoneBar'
import Slider from '../components/Slider'



export default function Home() {
 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SocailHeader/>
      <Header/>
      
      <PhoneBar/>
      <Slider/>
      <FeaturedCategories/>
      <Choose/>
      <Newsletter/>
      <Footer/>
      <CopyRight/>
     
    </>
  )
}
